import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FoldersSection from "./components/FoldersSection";
import { InboxContainer } from "./components/InboxContainer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen   ">
          <FoldersSection/>
          <InboxContainer/>
          {children}
        </main>

      </body>
    </html>
  );
}
