# Generated by Django 4.2.10 on 2024-02-23 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipient_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_email', to=settings.AUTH_USER_MODEL)),
                ('sender_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'emails',
                'ordering': ['-date'],
                'managed': True,
            },
        ),
    ]
